sudo: required
dist: xenial

matrix:
  include:
    - env: WITH_DOCKER=Y
      language: ruby
      services: docker
    - env: WITH_BUILDAH=Y

env:
  - GOPATH=/home/travis/go

install:
 - ./.travis/install_buildah.sh

script:
  - mkdir -p $GOPATH/{bin,pkg}
  - mkdir -p $GOPATH/src/github.com/nokia/danm/
  - mv * $GOPATH/src/github.com/nokia/danm/
  - cd $GOPATH/src/github.com/nokia/danm/
  - ./build_danm.sh